#!/bin/sh
#
# Copyright (c) 2017 Hannes von Haugwitz
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

STATE=$(systemctl is-system-running)

RETURN_CODE=0
MESSAGE=

case ${STATE} in
    running|initializing|starting)
        MESSAGE="OK: ${STATE}"
        ;;
    degraded|maintenance|stopping|offline|unknown)
        FAILED_SERVICES=$(systemctl --failed --no-legend --plain --full | cut -d '.' -f 1)
        NUM_FAILED=$(printf '%s' "${FAILED_SERVICES}" | wc -w)
        MESSAGE="CRITICAL: ${STATE} (${NUM_FAILED} failed unit(s): ${FAILED_SERVICES})"
        RETURN_CODE=2
        ;;
    *)
        MESSAGE="UNKNOWN: unsupported systemd state '${STATE}'"
        RETURN_CODE=3
        ;;
esac

echo "${MESSAGE}"
exit "${RETURN_CODE}"
