#!/bin/sh
#
# Copyright (c) 2017,2019 Hannes von Haugwitz
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

usage() {
    [ -n "${2}" ] && printf '%s: %s\n' "$(basename "${0}")" "${2}"
    printf 'usage: %s [-s] [-f interfaces_file] [-r autonegotiation_retries] [bondinterface=]interface[:state][,bondslave2[:bondstate2]...] ...\n' "$(basename "${0}")"
    exit "${1}"
}

merge_result() {
    if [ "${RETURN_CODE}" -eq "0" ] && [ "${1}" -gt "0" ]; then
        MESSAGE=
    fi
    if [ "${1}" -gt "0" ] || [ "${RETURN_CODE}" -eq "0" ]; then
        MESSAGE="${MESSAGE} ${INTERFACE}[${2}]"
    fi
    [ "${RETURN_CODE}" -lt "${1}" ] && RETURN_CODE=${1}
}

merge_result_negotiation() {
    NUM_RETRIES="$((RETRIES -N))"
    MSG="${2}"
    [ "${NUM_RETRIES}" -gt "0" ] && MSG="${MSG} (${NUM_RETRIES} auto-negotiations)"
    merge_result "${1}" "${MSG}"
}

check_bonding_interface() {
    BOND_INTERFACE="${1%%=*}"
    SLAVES="${1#*=}"
    check_interface "${BOND_INTERFACE}" 2 false
    IFS=','; for SLAVE in ${SLAVES}; do
        check_interface "${SLAVE}" 1 true
    done
}

renegotiate_speed() {
    ethtool -r "${INTERFACE}"
    i=15
    while [ "$(cat "/sys/class/net/${INTERFACE}/speed" 2> /dev/null)" -le "0" ] && [ "${i}" -gt "0" ]; do
        sleep 2
        i="$((i-1))"
    done
}

check_interface() {
    INTERFACE="${1%%:*}"
    EXPECTED_STATE="${1#*:}"
    DOWN_EXIT_CODE="${2}"
    RENEGOTIATABLE=${3}
    if [ -d "/sys/class/net/${INTERFACE}" ]; then
        if [ "$(cat "/sys/class/net/${INTERFACE}/carrier" 2> /dev/null)" = "1" ]; then
            if [ "${EXPECTED_STATE}" = "down" ]; then
                merge_result "${DOWN_EXIT_CODE}" "up"
            elif [ -n "${EXPECTED_STATE}" ] && [ "${EXPECTED_STATE}" != "${1}" ]; then
                N="${RETRIES}"
                while
                    INTERFACE_SPEED="$(cat "/sys/class/net/${INTERFACE}/speed" 2> /dev/null)"
                    if [ -n "${INTERFACE_SPEED}" ] ; then
                        if [ "${INTERFACE_SPEED}" -eq "${EXPECTED_STATE}" ]; then
                            merge_result_negotiation 0 "${INTERFACE_SPEED}Mb/s"
                        else
                            if ${RENEGOTIATABLE} && [ "${N}" -gt "0" ] ; then
                                renegotiate_speed
                            else
                                merge_result_negotiation 1 "${INTERFACE_SPEED}Mb/s != ${EXPECTED_STATE}Mb/s"
                            fi
                        fi
                    else
                        merge_result_negotiation 1 "invalid speed"
                    fi
                    :
                    N="$((N-1))"
                    [ -n "${INTERFACE_SPEED}" ] && [ "${INTERFACE_SPEED}" -ne "${EXPECTED_STATE}" ] && ${RENEGOTIATABLE} && [ "${N}" -ge "0" ]
                do :; done
            else
                merge_result 0 "up"
            fi
        else
            if [ "${EXPECTED_STATE}" != "down" ]; then
                merge_result "${DOWN_EXIT_CODE}" "down"
            else
                merge_result 0 "down"
            fi
        fi
    else
        merge_result 2 "not available"
    fi
}

RETURN_CODE=0
RETRIES=0
MESSAGE=
IFACES=
SYSLOG=false

while test ${#} -gt 0 ; do
    case ${1} in
        -h)
            usage 0
            ;;
        -r)
            if ! [ -x "$(command -v ethtool)" ] ; then
                printf '%s: %s\n' "$(basename "${0}")" "-r requires 'ethtool' to be installed!"
                exit 1
            fi
            case "${2}" in
                '')
                    usage 1 "-r needs an argument"
                    ;;
                *[!0-9]*)
                    usage 1 "${2} is not a positive number"
                    ;;
            esac
            RETRIES="${2}"
            shift
            ;;
        -f)
            [ -r "${2}" ] || usage 1 "cannot access '${2}'" 1>&2
            while read -r LINE ; do
                [ -n "${LINE}" ] && IFACES="${IFACES} ${LINE}"
            done < "${2}"
            shift
            ;;
        -s)
            SYSLOG=true
            ;;
        -*)
            usage 1 "unknown option '${1}'" 1>&2
            ;;
        *)
            IFACES="${IFACES} ${1}"
            ;;
    esac
    shift
done

[ -z "${IFACES}" ] && usage 1 "missing interface" 1>&2

for IFACE in ${IFACES} ; do
    case ${IFACE} in
        *=*)
            check_bonding_interface "${IFACE}"
            ;;
        *)
            check_interface "${IFACE}" 2 true
            ;;
    esac
done

case "${RETURN_CODE}" in
    0)
        MESSAGE="OK:${MESSAGE}"
        ;;
    1)
        MESSAGE="WARNING:${MESSAGE}"
        ;;
    2)
        MESSAGE="CRITICAL:${MESSAGE}"
        ;;
    3)
        MESSAGE="UNKNOWN:${MESSAGE}"
        ;;
esac

if ${SYSLOG}; then
    logger -i -t "$(basename "${0}")" "${MESSAGE}"
else
    printf '%s\n' "${MESSAGE}"
fi

exit "${RETURN_CODE}"
